spring.application.name=gateway
spring.cloud.config.uri=${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
spring.cloud.config.enabled=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.enabled=false

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=false
spring.cloud.gateway.globalcors.cors-configurations.[/**].max-age=3600