server:
  port: 8001
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/egress-db
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123}
  jpa:
    hibernate:
      ddl-auto: update
