server:
  port: 8081

eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: egress-ms
          uri: http://localhost:8001
          predicates:
            - Path=/egress/**

        - id: ingress-ms
          uri: http://localhost:8002
          predicates:
            - Path=/ingress/**

        - id: ingress-ms
          uri: http://localhost:8003
          predicates:
            - Path=/reports/**