server:
  port: 8081

eureka:
  client:
    enabled: false

spring:
  cloud:
    gateway:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: egress-ms
          uri: http://egress-microservice:8001
          predicates:
            - Path=/egress/**

        - id: ingress-ms
          uri: http://ingress-microservice:8002
          predicates:
            - Path=/ingress/**

        - id: ingress-ms
          uri: http://report-microservice:8003
          predicates:
            - Path=/reports/**