server:
  port: 8002
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:5432/${POSTGRES_DB_NAME}
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    enabled: false