apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-microservice-deployment
  template:
    metadata:
      labels:
        app: ingress-microservice-deployment
    spec:
      containers:
        - name: ingress-microservice-container
          image: locomotive1584/ingress-microservice:latest
          ports:
            - containerPort: 8002
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config:8888
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_INGRESS
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-microservice
spec:
  selector:
    app: ingress-microservice-deployment
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP