apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-microservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-microservice-deployment
  template:
    metadata:
      labels:
        app: report-microservice-deployment
    spec:
      containers:
        - name: report-microservice-container
          image: locomotive1584/report-microservice:latest
          ports:
            - containerPort: 8003
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config:8888
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_REPORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: GATEWAY_HOST
              value: "gateway"
            - name: GATEWAY_PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: report-microservice
spec:
  selector:
    app: report-microservice-deployment
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP