apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
data:
  POSTGRES_DB_HOST: "postgres"
  POSTGRES_DB_REPORT: "report-db"
  POSTGRES_DB_EGRESS: "egress-db"
  POSTGRES_DB_INGRESS: "ingress-db"